### ISSUE TITLE
Import connector in wso2 project

### ISSUE THREAD

**Issue by hectorcuper82** [wso2-extensions/esb-connector-feed#4]
Hi,

How can I import this connector into my wso2 project?

Kind Regards

**Comment by anupama-pathirage** [comment]
Please refer to the documentation https://ei.docs.wso2.com/en/7.0.0/micro-integrator/develop/creating-artifacts/adding-connectors/

If you have further issues please raise in https://github.com/wso2/micro-integrator/issues
